### ISSUE TITLE
about loss weight

### ISSUE THREAD

**Issue by he010103** [wanglimin/MRCNN-Scene-Recognition#12]
I found that in the train_val the loss_weight of kd-loss is set to 0.25. But in the paper the lambda is set to 0.5(The parameter of   = 0.5 is the best choice for scene network disambiguation for both normal BN-Inception and deeper BN-Inception architectures. ). Is there any wrong?

**Comment by wanglimin** [comment]
Please follow the paper. The provided protos are only for your reference.

**Comment by he010103** [comment]
Thanks you for your answer!
