### ISSUE TITLE
can you realse this flie ‘scene67_imagelist.mat’？

### ISSUE THREAD

**Issue by gsygsy96** [wanglimin/MRCNN-Scene-Recognition#3]
Hello Mr.Wang!
I am trying to test your demo.But I can't find the data file on the internet ,which is necessary in your code.It would be wonderful if you offer me this file! Thanks very much!

**Comment by wanglimin** [comment]
It is a file name list. You can generate the file list from your downloaded MIT indoor 67.

**Comment by gsygsy96** [comment]
yeah! I get it!
But another bug was arised:    
          错误使用 cat
          串联的矩阵的维度不一致。

         出错 test_mit67 (line 59)
          crop_data = cat(4, crop_data_1, crop_data_2, crop_data_3);

I thought if you have resized the crop_data to the same size before cat them in 4D?

**Comment by guoshengcv** [comment]
I think the upstair should check the  code carefully. @shanYanGuan
