### ISSUE TITLE
The speed of scene recognition

### ISSUE THREAD

**Issue by Li1991** [wanglimin/MRCNN-Scene-Recognition#4]
Dear author:
I am sorry to trouble you, but I just want to know the speed of this new method. Please tell me the information of GPU that you use. And how many pictures can you recognize during 1 second?
I am looking forward to getting your reply, thank you! @wanglimin

**Comment by wanglimin** [comment]
@Li1991 It takes about 0.03s to process a single forward for input 224*224.

**Comment by Li1991** [comment]
Can you tell me what kind of GPU you  use? @wanglimin

**Comment by wanglimin** [comment]
TitanX @Li1991
