### ISSUE TITLE
SoftmaxWithCrossEntropyLoss:unknow layer type

### ISSUE THREAD

**Issue by gsygsy96** [wanglimin/MRCNN-Scene-Recognition#5]
When I scan your code file(modles/kd_train/*_train_val.prototxt) yesterday,I found an unkonw layer type named SoftmaxWithCrossEntropyLoss which output 'kd-loss'.I have checked a lot of information include [caffe wrote by yjxiong](https://github.com/yjxiong/caffe/tree/kd),but I still can't find some information about it. 
Maybe I can replace it with SigmoidCrossEntropyLossLayer?

**Comment by wanglimin** [comment]
You should use the kd branch:

https://github.com/yjxiong/caffe/tree/kd

**Comment by wanglimin** [comment]
Here is the implementation:

https://github.com/yjxiong/caffe/blob/kd/src/caffe/layers/softmax_cross_entropy_loss_layer.cu

**Comment by gsygsy96** [comment]
@wanglimin oh...I see...Sincerely appreciating your guide! Thank you very much!
