### ISSUE TITLE
About permutation of width and height

### ISSUE THREAD

**Issue by ghost** [wanglimin/MRCNN-Scene-Recognition#7]
Hi, 

Many thanks for sharing. Truly appreciate your amazing works.

I was going to apply your pre-trained model to my own dataset; however, the permutation of input images' height and width makes me confused: 

At line 33 of matlab/test_places2.m and line 40 of matlab/test_mit67.m, you performed
**im_data = permute(im_data, [2, 1, 3]); % permute width and height**

So, you rearrange the shape of the input image from **(height, width, depth)** to **(width, height, depth)**, where depth=3 reflecting 'BGR' color channels; am I right?

Could you please explain a little bit on this operation? Is it a convention to do this, or there are other deeper reasons?

BTW: I'm using OpenCV with Python instead of Matlab. In Python, the image is loaded of shape (height, width, depth='bgr'); and I noticed that for Caffe, the conventional blob dimensions for batches of image data are **number N x channel K x height H x width W**. I'm not sure if there's any relation with the permutation.

Thanks for your time.

**Comment by wanglimin** [comment]
This is the standard operation to deal with the memory difference of image data between Matlab and Caffe. For more details, please refer to:

https://github.com/BVLC/caffe/blob/master/matlab/demo/classification_demo.m#L128

**Comment by ghost** [comment]
Thank you so much for your prompt reply. The given link has resolved my doubts.
