### ISSUE TITLE
Need help for test the code

### ISSUE THREAD

**Issue by mksarker** [wanglimin/MRCNN-Scene-Recognition#8]
Hello, 
I am unable to test the code by using the instructions as you described here. The error as below;

Attempt to reference field of non-structure array.
Error in test_places2 (line 16)
file_list = tmp.textdata;

I have another question;
What should be the following files are;

file_name = 'places2/val_result.mat';
val_file = 'places365_val.txt';

Thanks in advanced.

**Comment by wanglimin** [comment]
Val_file is the filelist of validation images, which could be downloaded from the Places2 dataset.
file_name is the name of your score file.

**Comment by mksarker** [comment]
Hi,
Thank you very much for your reply and suggestions.
I have follow your instructions but got error as;
Attempt to reference field of non-structure array.

Error in test_places2 (line 17)
file_list = tmp.textdata;

Please help me with tis issue.

**Comment by guoshengcv** [comment]
I think you need to check your matlab code.  This code run the val dataset, the txt file  have the label informantion,  you run the test datast, you only change "file_list = tmp.textdata" to  "file_list = tmp"

**Comment by mksarker** [comment]
Thanks @guoshengcv  for your information and guideline.
After run your code I got the score file. Now, please help me how to calculate top-5 and top-1 acc in your code for make sure your model is working well in my system and also, I can see my dataset performance with your models. Thanks in advanced.

**Comment by guoshengcv** [comment]
The code to calculate top5 and top1 acc is very easy,  you can find the detail from http://image-net.org/challenges/LSVRC/2016/. I'm sure you can write this code very soon.  Thanks.

**Comment by mksarker** [comment]
Thanks @guoshengcv  again for valuable info.
