### ISSUE TITLE
Message type "caffe.BatchNormParameter" has no field named "engine"

### ISSUE THREAD

**Issue by IamMegatron2025** [wanglimin/MRCNN-Scene-Recognition#9]
您好，我自己写了一个python脚本
```
MODEL_FILE = 'models/standard_train/256_inception2_deploy.prototxt';
PRETRAINED = 'models/places2_standard_256_inception2_v5.caffemodel';
caffe_root="/home/xxx/work/deeplearning-tools/caffe/caffe-v0.9999"
import caffe

#GPU模式
caffe.set_mode_gpu()
#定义使用的神经网络模垿
net = caffe.Classifier(MODEL_FILE, PRETRAINED,
               mean=np.load(os.path.join(caffe_root,'python/caffe/imagenet/ilsvrc_2012_mean.npy')).mean(1).mean(1),
               channel_swap=(2,1,0),
               raw_scale=255,
               )
## execute 
sample = caffe.io.load_image("Places365_val_00000041.jpg")

#预测图片类别
prediction = net.predict([sample])
```
来测试您的模型，报错如下：
`Message type "caffe.BatchNormParameter" has no field named "engine"`
我google了一下这个错误，没有找到答案，能给点建议吗？
谢谢！

**Comment by wanglimin** [comment]
Which caffe did you use?

**Comment by IamMegatron2025** [comment]
@wanglimin the version is caffe-v0.9999

**Comment by wanglimin** [comment]
You should use our customized Caffe at:

https://github.com/yjxiong/caffe/tree/kd

**Comment by IamMegatron2025** [comment]
@wanglimin thank you. this caffe solves my problem.
Now I have another question. I want to get top_5 using `top_k = net.blobs['prob'].data[0].flatten().argsort()[-1:-6:-1]`, but it shows error:
```
Traceback (most recent call last):
  File "test.py", line xxx, in <module>
    top_k = net.blobs['prob'].data[0].flatten().argsort()[-1:-6:-1]
KeyError: 'prob'
```
so, can not I get top_k through `net.blobs['prob']`? And how should I obtain?

**Comment by wanglimin** [comment]
You should check your proto file and see whether it has a blob named as 'prob'

**Comment by IamMegatron2025** [comment]
@wanglimin thank you. I get what I want to get through `net.blobs['prob']`.
